### PR TITLE
Feature: Mac build

### PR DESCRIPTION
**Pull request by dgslomin**
Minor modifications to build and run on the Mac.  Tested on MacOS 10.14.6 using
"Not a Hat SimpleSynth" to verify that MIDI output works properly.  The Mac
".icns" icon was converted verbatim from the Windows ".ico" version.

### CODE REVIEW

**Comment by dgslomin** [comment]
May I offer you a minimal modification so that MidiEditor can run on the Mac?  You've written wonderfully portable code to begin with, and your few dependencies (Qt and RTMidi) are also very portable, so almost no effort was needed.

**Comment by markusschwenk** [comment]
Great, thank you!

After verifying that everything runs smooth, on mac, can we also add packaging?

I actually do not fully understand why DEPLOY_BINARIY=releases/MidiEditor-$MIDIEDITOR_RELEASE_VERSION_STRING-mac.tar.gz; 

is created. Should'nt the output be just an executable and we'd have to have a packaging script as well?

**Comment by dgslomin** [comment]
Traditionally Mac software doesn't really use packages; well-behaving apps are fully contained inside their executables (app bundles).  They can be run from anywhere, or the user can drag them into the "applications" folder where system apps are preinstalled.

Sometimes folks will create a disk image containing a single folder with two items in it:  the executable and a shortcut to the applications folder.  This makes it easy for the user to open the disk image in the finder and drag the executable onto the shortcut, which copies the app into the applications folder.  I've always thought it's a little gratuitous but it doesn't do any harm.  Is this what you had in mind?  I can look up how to set that up in a scripted manner instead of just sticking the executable in a tarball.

**Comment by daslomin-microsoft** [comment]
I tested the Mac version with my large sample file (237 kB, 40 minutes of live piano playing) and there wasn't any noticeable different in performance there compared to the other platforms.  It handles it just fine.

**Comment by markusschwenk** [comment]
Merging this now, we can decide about the portable format. Probably you know it better than me, since I'm not familiar with Mac at all.

**Pull request merged**
