### PR TITLE
Feature: Tweak editing

### PR DESCRIPTION
**Pull request by dgslomin**
add an interface for precision editing of event properties (tweaking)

Add a "tweak" submenu under "tools" that allows the user to navigate through
the file and tweak the properties of each event using the keyboard.  The target
audience is someone manually polishing a live recording.

### CODE REVIEW

**Comment by dgslomin** [comment]
This is a larger review than the others, since it corresponds to a full new feature rather than a small increment on existing ones.  There's even a little trigonometry in it, which I didn't expect to need for this kind of application, but it turned out to be relevant.  More than anything else, the lack of this kind of interface is what made me seek out alternatives to the likes of Cubase.

**Comment by markusschwenk** [comment]
Love it! Navigation becomes superb after this change :)

However, a few things to refactor:
I think the navigation used here (ALT+left etc) should be default, and moved out of the Tweak toolbar.
We can remove the old navigation and the meaning of left / right arrow keys (currently they're just moving the cursor). 

Do we have shortcuts for the actual tweaking? I see only 1 - 4 for "what" to tweak, but we need them also for increase / decrease etc.

Also, could you add manual section about the tool?

**Comment by dgslomin** [comment]
Yes, I agree that this type of navigation isn't just related to tweak editing.  Should it go into the edit menu?  It's not actually related to playback, so it doesn't seem right there.

In fact, I see a lot of value in having both types of navigation -- this moves the selection whereas the existing one moves the playback cursor.  Both are definitely useful and I wouldn't want to lose the ability to do the latter.  Would you want to swap the keybindings so that this is the one that doesn't require a modifier?

Hmm, on both Mac and Windows, the increase and decrease show up as having the square brackets as keybindings (with the alt modifier for the large variation).  I didn't think to check if that worked on Linux.  I ran into a similar problem in the past where keybindings that didn't use any modifiers wouldn't work on Linux unless I added an additional handler beyond the normal one that comes with setting up a menu item, but that was when I was using Wx rather than Qt.  I'll experiment with it tomorrow.

As for the manual, I agree this definitely needs it; I just wanted to work out the proper menu layout, keybindings, etc with you first.

**Comment by dgslomin** [comment]
I just double-checked on Linux, and the following both appear in the menu and function properly from the keyboard:

- Tools/Tweak/Time (start and end together) = 1
- Tools/Tweak/Start time = 2
- Tools/Tweak/End time = 3
- Tools/Tweak/Note = 4
- Tools/Tweak/Value (velocity, controller value, tempo, etc - the things you can edit in the misc widget) = 5
- Tools/Tweak/Small decrease = [
- Tools/Tweak/Small increase = ]
- Tools/Tweak/Large decrease = Alt+[
- Tools/Tweak/Large increase = Alt+]

Could it be that when you tried it, you only did a small increase of time (the default)?  That has only a very subtle visual effect, but you can see it by repeating the action a few times, or by observing it in the event widget.

**Comment by markusschwenk** [comment]
Interesting, on Ubuntu I didn't see the binding in the menu, and since I didn't read the code I didn't know the shortcut:)
We should eventually move towards bindings being adjustable view settings.
Until then, what about using+ and- in since combination? (Ctrl  (alt)+/- or so).

Yes, move the navigation to the edit menu and swap the bindings!

Thanks

**Comment by daslomin-microsoft** [comment]
Weird about Ubuntu - I'm running Kubuntu (albeit a somewhat old version) and I see them there.

As for switching to different keybindings, you've already used plus and minus for zoom, which has the advantage of being the expected standard.  Looking up the Swiss QWERTZ keyboard standard, I can see why you might encounter trouble that I don't see with an American QWERTY keyboard.  You don't have dedicated keys for the square brackets like I do; you need the Alt-Gr modifier to get to them.  What if we used 9 for decrease and 0 for increase?  Those are the same on both keyboard layouts, are physically adjacent to one another, and group together with the "select the tweak target" keybindings on the lower number keys.

**Comment by markusschwenk** [comment]
Thanks a lot! The navigation in the edit menu makes sense, also the new bindings.
Merging now.

**Pull request merged**
