### PR TITLE
Feature: tempo editing in the MiscWidget

### PR DESCRIPTION
**Pull request by dgslomin**

### CODE REVIEW

**Comment by markusschwenk** [comment]
Thanks a lot! Great idea to add the tempo in this widget!

Two comments:
1.)
I tried it on linux, and it appears that, when using free-hand or line mode to add transitions in the tempo, existing events in the given time range are not deleted.
image

This screenshot was taken after using line mode once up and once down. The latest line should be permanent, and the end point set the tempo until the very next tempo change event.
 
2.) Could you add an update to the manual? I think there's either a description about tempo changes, but there should also be a section about the misc widget.

**Comment by dgslomin** [comment]
Oops, looks like I have some debugging to do.  I didn't think to test the freehand and line modes since I'm most interested in editing existing events myself, and was very closely basing the tempo code on the existing code for editing controllers, etc.  I must have missed a case.

I'll also do the manual bits.

**Comment by markusschwenk** [comment]
Thanks for fixing!
However, I still end up with max tempo sometimes (was  not able to figure out a way to always reproduce) at the end of the time frame I modified using free-hand or linear tool. Could you check?

**Comment by dgslomin** [comment]
Note to self: probably coming from the X coordinate of later events
changing when a tempo event is inserted.  May need two passes, one to
compute where all the events of a drag gesture should be inserted
(translating from pixels to midi ticks based on existing events), then a
second pass to do the inserts.  Other event types don’t affect the
linearity pf the X axis, which is why symmetry in the code wasn’t
sufficient.

**Comment by daslomin-microsoft** [comment]
Nope, still no good.  The extrapolation is causing some undesirable effects.  I'll keep poking at it.

**Pull request merged**
